version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    container_name: postgres
    environment:
      POSTGRES_USER: tracker
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: pipeline_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  neo4j:
    image: neo4j:5
    restart: always
    container_name: neo4j
    ports:
      - "7474:7474" # Web UI
      - "7687:7687" # Bolt protocol (för Go-anslutning)
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - neo4j_data:/data

volumes:
  pgdata:
  neo4j_data:
